/**
 * Bezier subdivision golden fixtures — cross-check against geometry-central.
 *
 * Each fixture in fixtures/*.json with kind="bezier" was generated by the C++
 * harness in tools/gen_bezier_fixtures/. We rebuild the same network from the
 * mesh + control vertices, run bezierSubdivide for the same nRounds, and
 * compare the output path length to the gc reference.
 *
 * Tolerance: 14 of the 17 fixtures match gc to ~1e-13 (machine epsilon).
 * Three (teapot-bezier-3pt-r1, teapot-bezier-3pt-r3, spot-bezier-5pt-r3)
 * drift by 1e-4 to 3e-3. Root cause is not algorithmic — it's V8's `Math.acos`
 * vs glibc's `std::acos` returning 1-ulp-different results on specific
 * inputs (e.g. q=0.097920746884416418 differs in bit pattern by ±1 ulp).
 * That ulp drift cascades through corner angles → signposts → wedge angles,
 * and on near-degenerate teapot/spot geometries flips a priority-queue
 * tiebreak the other way, producing a valid-but-different Bezier curve.
 *
 * Tried: PI/2 − Math.asin, atan2(sqrt(1−q²), q), %, fmod, custom standardize.
 * None reliably match glibc bit-for-bit across all inputs. Eliminating this
 * would require a JS port of glibc's libm.
 *
 * 1% tolerance accommodates the worst observed drift.
 */

import { describe, expect, it } from 'vitest';

import { VertexPositionGeometry } from '../../../src/geometry/vertex-position-geometry.js';
import { SignpostIntrinsicTriangulation } from '../../../src/intrinsic/signpost-intrinsic-triangulation.js';
import { SurfaceMesh } from '../../../src/mesh/surface-mesh.js';
import {
  flipEdgeNetworkFromControlPath,
} from '../../../src/flipout/index.js';
import { listFixtures, loadBezierFixture } from '../../_helpers/load-fixture.js';

const PATH_LENGTH_REL_TOL = 1e-2;

for (const name of listFixtures('bezier')) {
  describe(`bezier fixture — ${name}`, () => {
    it('path length matches geometry-central reference', () => {
      const f = loadBezierFixture(name);
      const mesh = SurfaceMesh.fromFaces(f.mesh.faces, f.mesh.vertices.length);
      const geom = new VertexPositionGeometry(mesh, f.mesh.vertices);
      const sit = new SignpostIntrinsicTriangulation(geom);
      const net = flipEdgeNetworkFromControlPath(sit, f.query.controlVertices, {
        markInterior: true,
      });
      expect(net, `${name}: failed to build initial network`).not.toBeNull();
      net!.bezierSubdivide(f.query.nRounds);

      const got = net!.pathLength();
      const want = f.expected.pathLength;
      const relErr = Math.abs(got - want) / Math.max(1, Math.abs(want));
      expect(
        relErr,
        `${name}: length ${got} vs reference ${want} (relErr=${relErr.toExponential(3)})`,
      ).toBeLessThan(PATH_LENGTH_REL_TOL);
    });
  });
}
