/**
 * Test-only helper for loading FlipOut golden fixtures.
 *
 * Fixtures are JSON files under `<repo>/fixtures/`, generated by either:
 *   - `tools/gen_fixtures.py`            → kind="geodesic", schema_version 1
 *   - `tools/gen_bezier_fixtures/...`    → kind="bezier",   schema_version 2
 *
 * They live outside `src/` and are never bundled — only the test suite reads
 * them. Resolution is anchored at the repo root via `import.meta.url` so the
 * helper works regardless of the test runner's cwd.
 *
 * Schema version 1 fixtures predate the `kind` field; missing kind is treated
 * as "geodesic" for back-compat.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export type FixtureKind = 'geodesic' | 'bezier';

interface BaseFixture {
  schemaVersion: number;
  kind: FixtureKind;
  name: string;
  mesh: {
    vertices: [number, number, number][];
    faces: [number, number, number][];
  };
}

export interface GeodesicFixture extends BaseFixture {
  kind: 'geodesic';
  query: { src: number; dst: number };
  expected: {
    pathLength: number;
    pathPoints: [number, number, number][];
  };
}

export interface BezierFixture extends BaseFixture {
  kind: 'bezier';
  query: {
    controlVertices: number[];
    nRounds: number;
    closed: boolean;
  };
  expected: {
    pathLength: number;
    pathPoints: [number, number, number][];
  };
}

export type Fixture = GeodesicFixture | BezierFixture;

interface RawFixture {
  schema_version: number;
  kind?: FixtureKind;
  name: string;
  note?: string;
  mesh: {
    vertices: number[][];
    faces: number[][];
  };
  // Geodesic
  query: {
    src?: number;
    dst?: number;
    control_vertices?: number[];
    n_rounds?: number;
    closed?: boolean;
  };
  expected: {
    path_length: number;
    path_points: number[][];
  };
  potpourri3d_version?: string;
  geometry_central_sha?: string;
}

const HERE = dirname(fileURLToPath(import.meta.url));
// repo root: test/_helpers -> test -> repo
const FIXTURE_DIR = resolve(HERE, '..', '..', 'fixtures');

function asTriple(arr: number[], context: string): [number, number, number] {
  if (arr.length !== 3) {
    throw new Error(
      `${context}: expected length-3 array, got length ${arr.length}`,
    );
  }
  // After the length check above each index is in-bounds; the non-null
  // assertions are needed because of `noUncheckedIndexedAccess`.
  return [arr[0]!, arr[1]!, arr[2]!];
}

function readRaw(name: string): RawFixture {
  const path = join(FIXTURE_DIR, `${name}.json`);
  const raw = readFileSync(path, 'utf8');
  return JSON.parse(raw) as RawFixture;
}

function rawKind(raw: RawFixture): FixtureKind {
  // schema v1 predates `kind`; treat missing as geodesic.
  return raw.kind ?? 'geodesic';
}

function buildMesh(name: string, raw: RawFixture): BaseFixture['mesh'] {
  return {
    vertices: raw.mesh.vertices.map((v, i) =>
      asTriple(v, `${name} vertex[${i}]`),
    ),
    faces: raw.mesh.faces.map((f, i) => asTriple(f, `${name} face[${i}]`)),
  };
}

function buildPathPoints(
  name: string,
  raw: RawFixture,
): [number, number, number][] {
  return raw.expected.path_points.map((p, i) =>
    asTriple(p, `${name} path_points[${i}]`),
  );
}

/**
 * Load a geodesic fixture by name (without the .json suffix).
 *
 * Throws if the file is missing, has an unsupported schema version, or is a
 * bezier fixture. For bezier fixtures use {@link loadBezierFixture}.
 */
export function loadFixture(name: string): GeodesicFixture {
  const raw = readRaw(name);
  if (raw.schema_version !== 1) {
    throw new Error(
      `Fixture ${name}: schema_version ${raw.schema_version} ` +
        `not supported by loadFixture (expected 1). ` +
        `Use loadBezierFixture for bezier fixtures.`,
    );
  }
  const kind = rawKind(raw);
  if (kind !== 'geodesic') {
    throw new Error(
      `Fixture ${name}: kind=${kind}; loadFixture only handles geodesic. ` +
        `Use loadBezierFixture instead.`,
    );
  }
  if (raw.query.src === undefined || raw.query.dst === undefined) {
    throw new Error(`Fixture ${name}: geodesic query missing src/dst`);
  }
  return {
    schemaVersion: raw.schema_version,
    kind: 'geodesic',
    name: raw.name,
    mesh: buildMesh(name, raw),
    query: { src: raw.query.src, dst: raw.query.dst },
    expected: {
      pathLength: raw.expected.path_length,
      pathPoints: buildPathPoints(name, raw),
    },
  };
}

/**
 * Load a bezier fixture by name (without the .json suffix).
 *
 * Throws if the file is missing, has an unsupported schema version, or is not
 * a bezier fixture.
 */
export function loadBezierFixture(name: string): BezierFixture {
  const raw = readRaw(name);
  if (raw.schema_version !== 2) {
    throw new Error(
      `Fixture ${name}: schema_version ${raw.schema_version} ` +
        `not supported by loadBezierFixture (expected 2).`,
    );
  }
  const kind = rawKind(raw);
  if (kind !== 'bezier') {
    throw new Error(
      `Fixture ${name}: kind=${kind}; loadBezierFixture only handles bezier.`,
    );
  }
  if (
    raw.query.control_vertices === undefined ||
    raw.query.n_rounds === undefined
  ) {
    throw new Error(
      `Fixture ${name}: bezier query missing control_vertices / n_rounds`,
    );
  }
  return {
    schemaVersion: raw.schema_version,
    kind: 'bezier',
    name: raw.name,
    mesh: buildMesh(name, raw),
    query: {
      controlVertices: [...raw.query.control_vertices],
      nRounds: raw.query.n_rounds,
      closed: raw.query.closed ?? false,
    },
    expected: {
      pathLength: raw.expected.path_length,
      pathPoints: buildPathPoints(name, raw),
    },
  };
}

/**
 * List fixture names available in the fixtures directory (without the .json
 * suffix). When `kind` is given, returns only fixtures of that kind; otherwise
 * returns every fixture.
 */
export function listFixtures(kind?: FixtureKind): string[] {
  const all = readdirSync(FIXTURE_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.slice(0, -'.json'.length))
    .sort();
  if (kind === undefined) return all;
  return all.filter((name) => rawKind(readRaw(name)) === kind);
}
