/**
 * Test-only helper for loading FlipOut golden fixtures.
 *
 * Fixtures are JSON files under `<repo>/fixtures/`, generated by
 * `tools/gen_fixtures.py`. They live outside `src/` and are never bundled —
 * only the test suite reads them.
 *
 * Resolution is anchored at the repo root via `import.meta.url` so the
 * helper works regardless of the test runner's cwd.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface Fixture {
  schemaVersion: number;
  name: string;
  mesh: {
    vertices: [number, number, number][];
    faces: [number, number, number][];
  };
  query: { src: number; dst: number };
  expected: {
    pathLength: number;
    pathPoints: [number, number, number][];
  };
}

interface RawFixture {
  schema_version: number;
  name: string;
  note?: string;
  mesh: {
    vertices: number[][];
    faces: number[][];
  };
  query: { src: number; dst: number };
  expected: {
    path_length: number;
    path_points: number[][];
  };
  potpourri3d_version?: string;
}

const SUPPORTED_SCHEMA_VERSION = 1;

const HERE = dirname(fileURLToPath(import.meta.url));
// repo root: test/_helpers -> test -> repo
const FIXTURE_DIR = resolve(HERE, '..', '..', 'fixtures');

function asTriple(arr: number[], context: string): [number, number, number] {
  if (arr.length !== 3) {
    throw new Error(
      `${context}: expected length-3 array, got length ${arr.length}`,
    );
  }
  // After the length check above each index is in-bounds; the non-null
  // assertions are needed because of `noUncheckedIndexedAccess`.
  return [arr[0]!, arr[1]!, arr[2]!];
}

/**
 * Load a fixture by name (without the .json suffix).
 * Throws if the file is missing or has an unsupported schema version.
 */
export function loadFixture(name: string): Fixture {
  const path = join(FIXTURE_DIR, `${name}.json`);
  const raw = readFileSync(path, 'utf8');
  const data = JSON.parse(raw) as RawFixture;

  if (data.schema_version !== SUPPORTED_SCHEMA_VERSION) {
    throw new Error(
      `Fixture ${name}: schema_version ${data.schema_version} ` +
        `not supported (expected ${SUPPORTED_SCHEMA_VERSION}). ` +
        `Regenerate with tools/gen_fixtures.py.`,
    );
  }

  return {
    schemaVersion: data.schema_version,
    name: data.name,
    mesh: {
      vertices: data.mesh.vertices.map((v, i) =>
        asTriple(v, `${name} vertex[${i}]`),
      ),
      faces: data.mesh.faces.map((f, i) => asTriple(f, `${name} face[${i}]`)),
    },
    query: { src: data.query.src, dst: data.query.dst },
    expected: {
      pathLength: data.expected.path_length,
      pathPoints: data.expected.path_points.map((p, i) =>
        asTriple(p, `${name} path_points[${i}]`),
      ),
    },
  };
}

/**
 * List all fixture names available in the fixtures directory (without
 * the .json suffix). Useful for parametrizing tests.
 */
export function listFixtures(): string[] {
  return readdirSync(FIXTURE_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.slice(0, -'.json'.length))
    .sort();
}
